version: '3.8'

services:
  tesisladespensa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - backend/src/config/.env
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend